### ISSUE TITLE
How to increase time for a job that is getting a TIMEOUT error?

### ISSUE THREAD

**Issue by scottdaniel** [shandley/hecatomb#122]
I'm very confused as to which config file specifies the running time that hecatomb requests from the cluster for a job.

I'm running out of time with a `secondary_nt_lca_table` job and from the log file I see that the resources are:
`resources: mem_mb=16000, mem_mib=15259, disk_mb=1000, disk_mib=954, tmpdir=/tmp, account=hpcusers, partition=defq, time=01:00:00, mem=16000MB`

What's weird is that this doesn't match what I have in my ~/.config/snakemake/slurm/config.yaml:
```
default-resources:
- account="hpcusers"
- partition="defq"
- time=720
- mem_mb=8000
- disk_mb=1000
```

Nor does it match anything in my `hecatomb.config.yaml`

Is there some secret file that specifies resources just for `secondary_nt_lca_table`? How do I increase the time limit for this job?

**Comment by scottdaniel** [comment]
My hecatomb.config.yaml:
```
hecatomb:
  addHost:
    minViralAlnLen: 1000
  args:
    assembly: merged
    conda_prefix: /home/danielsg/miniconda3/envs/hecatomb/lib/python3.12/site-packages/hecatomb/snakemake/conda
    configfile: /scr1/users/danielsg/hecatomb.out_jiayi_def/hecatomb.config.yaml
    custom_aa: null
    custom_nt: null
    example_profile: false
    fastqc: false
    host: human
    log: /scr1/users/danielsg/hecatomb.out_jiayi_def/hecatomb.log
    longreads: false
    output: /scr1/users/danielsg/hecatomb.out_jiayi_def
    profile: slurm
    reads: /mnt/isilon/microbiome/shared_folders/jiayi_defined_community/demuxed
    search: sensitive
    simulate: false
    snake_args: []
    system_config: /home/danielsg/miniconda3/envs/hecatomb/lib/python3.12/site-packages/hecatomb/snakemake/config/config.yaml
    system_workflow_profile: /home/danielsg/miniconda3/envs/hecatomb/lib/python3.12/site-packages/hecatomb/snakemake/profile/default/config.yaml
    threads: 8
    trim: fastp
    use_conda: true
    workflow_profile: /scr1/users/danielsg/hecatomb.out_jiayi_def/hecatomb.profile
  assembly:
    canu: correctedErrorRate=0.16 maxInputCoverage=10000 minInputCoverage=0 corOutCoverage=10000
      corMhapSensitivity=high corMinCoverage=0 useGrid=False stopOnLowCoverage=False
      genomeSize=10M -nanopore
    flye: -g 1g
    megahit: --presets meta-large
    metaflye: --meta -g 1g --nano-raw
  mmseqs:
    fast: -s 4
    filtAA: --min-length 30 -e 1e-5
    filtNT: --min-length 90 -e 1e-20
    linclustParams: --kmer-per-seq-scale 0.3 -c 0.8 --cov-mode 1 --min-seq-id 0.97
      --alignment-mode 3
    sensitive: --start-sens 2 --sens-steps 3 -s 7
    taxIdIgnore: 0 1 2 10239 131567 12429 2759
resources:
  big:
    cpu: 32
    mem: 64000
    time: '24:00:00'
  lrg:
    cpu: 16
    mem: 32000
    time: 04:00:00
  med:
    cpu: 8
    mem: 16000
    time: 04:00:00
  ram:
    cpu: 2
    mem: 16000
    time: 04:00:00
  sml:
    cpu: 1
    mem: 2000
    time: 01:00:00
trimnami:
  qc:
    compression: 1
    cutadapt: -m 40
    fastp: --qualified_quality_phred 15 --length_required 90 --cut_tail --cut_tail_window_size
      25 --cut_tail_mean_quality 15 --dedup --dup_calc_accuracy 4 --trim_poly_x --detect_adapter_for_pe
    filtlong: --min_length 1000 --keep_percent 95
    hostRemoveFlagstat: -f 4 -F 3584
    minimapIndex: -I 8G
    prinseq: -min_len 60 -min_qual_mean 25 -ns_max_n 1 -derep 1 -out_format 0 -trim_tail_left
      5 -trim_tail_right 5 -ns_max_n 5 -trim_qual_type min -trim_qual_left 30 -trim_qual_right
      30 -trim_qual_window 10
```

and the full config.yaml for under ~/.config/snakemake/slurm/
```
cluster:
  mkdir -p logs/{rule}/ &&
  sbatch
    --account={resources.account}
    --partition={resources.partition}
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --time={resources.time}
    --parsable
    --job-name=smk-{rule}
    --output=logs/{rule}/{jobid}.out
    --error=logs/{rule}/{jobid}.err
default-resources:
  - account="hpcusers"
  - partition="defq"
  - time=720
  - mem_mb=8000
  - disk_mb=1000
jobs: 42
latency-wait: 90
local-cores: 8
restart-times: 1
max-jobs-per-second: 20
keep-going: True
rerun-triggers: "mtime"
rerun-incomplete: True
verbose: True
nolock: True
notemp: True
printshellcmds: True
scheduler: greedy
use-conda: True
conda-frontend: mamba
cluster-status: ~/.config/snakemake/slurm/slurm-status.py
max-status-checks-per-second: 10
```

**Comment by scottdaniel** [comment]
Ok, using clues from other issues, I think I figured it out. I looked up the code for `[secondary_nt_lca_table](https://github.com/shandley/hecatomb/blob/06ef76767078b6f2eeb49c6889ebe68e3c7a60b8/hecatomb/snakemake/workflow/rules/annotation/read_annotation.smk#L300)` and found this
```
resources:
        time = resources["sml"]["time"],
        mem_mb=resources["ram"]["mem"],
        mem=str(resources["ram"]["mem"]) + "MB",
```

So I went in to my hecatomb.config.yaml and increased the time requirements for `sml` jobs:
```
sml:
    cpu: 1
    mem: 2000
    time: 04:00:00 #01:00:00
```

Voila! of course, this means all `sml` jobs have more time requested. It would be nice to allow for rule specific time allocations. More importantly, this should be somewhere in the docs.
